### ISSUE TITLE
Example of static content on hunchentoot/heroku

### ISSUE THREAD

**Issue by pnathan** [jsmpereira/heroku-cl-example#2]
Mtravers had an example of a static file; I've been working to try and get that going in the hunchentoot/heroku environment, but I've had no success. It would be very handy to use, e.g., for pictures and such.

I've reflected upon http://stackoverflow.com/questions/8285115/how-to-tell-hunchentoot-where-to-find-static-web-pages-to-serve, but no dice.

**Comment by jsmpereira** [comment]
Yes indeed. I'll take a look. Thanks

**Comment by pnathan** [comment]
If you want any information, I will  be happy to give it or test snippets.

On Mar 17, 2012, at 3:59 PM, Jos Santos Martins Pereira wrote:

> Yes indeed. I'll take a look. Thanks
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jsmpereira/heroku-cl-example/issues/2#issuecomment-4557850

Regards,
Paul Nathan

**Comment by pnathan** [comment]
The first argument to create-folder-dispatcher-and-handler needs to be surrounded with /

   (push
     (hunchentoot:create-folder-dispatcher-and-handler
      "/static/"
      "/app/public/")
     hunchentoot:_dispatch-table_)

Once this is done, it should work.

**Comment by jsmpereira** [comment]
Added in d12585ee1c93094937070ab414a89a753c75a88f .

Thanks Paul.

**Comment by avodonosov** [comment]
@pnathan what guarantees that /app/ folder contains the application sources? I see it is working, but do not understand how. The buildpack doesn't copy the sources anywhere. Does heroku guarantee that /app/ directory contain the sources?

**Comment by pnathan** [comment]
I don't remember offhand( at work at the moment). I think I determined it experimentally, ie, poke around until I figured out what seemed to work. My apologies. Would you like me to dig around some more in a few hours?

Regards, 
Paul Nathan

**Comment by avodonosov** [comment]
02.02.2013, 04:42, "Paul Nathan" notifications@github.com:

> I don't remember offhand( at work at the moment). I think I determined it experimentally, ie, poke around until I figured out what seemed to work. My apologies. Would you like me to dig around some more in a few hours?

I would like to know how reliable it is. Is it guaranteed by Heroku in some documentation, or it's just their private solution which can be changed anytime. I am looking for such documentation myself now. If you remember or find something I will appreciate help. But no urgency for me.

**Comment by jsmpereira** [comment]
Hi. 

The /app folder is the root of your application on the heroku system.

The buildpack sets up the runtime environment and builds your app in /tmp which then gets copied over to /app. This is how Heroku slugs work.

Hope that helped.

Cheers,
José Santos

**Comment by avodonosov** [comment]
It helps a little.

So you say it is reliable to refer /app? Can Heroku change it tomorrow to /application or something else? I can't find the "/app/" directory explicitly specified in Heroku documentation.

PS, note that our buildpack doesn't copy the sources, only CCL binary and application image. Still, the sources are available on the slug. I am trying to determine exactly the question about sources (repository content). Is it guaranteed to present in /app/

**Comment by jsmpereira** [comment]
The stuff added by the buildpack is done here https://github.com/jsmpereira/heroku-buildpack-cl/blob/master/bin/compile#L89 .

Everything else should be the contents of your local repository and when you push to Heroku it will get packaged into a slug and will live under /app.

I also haven't found any reference in the docs to the /app directory explicitly, but it seems to be a convention from their Slug Compiler.

**Comment by jsmpereira** [comment]
After a nice chat in #heroku at irc.freenode.org with @yfeldblum some more info:

The folder /app is indeed not documented and is an implementation detail of the current Heroku Stack.
Its probably not a good idea to be hardcoding /app. :P

We can get that information from environment variables such as PWD or HOME.

**Comment by avodonosov** [comment]
Thanks for the info.

Is the $HOME is documented to contain the sources? 
:)

**Comment by jsmpereira** [comment]
I've tried both $PWD and $HOME and it seems that only $HOME serves our needs. For now.

Inside [src/hello-world.lisp](https://github.com/jsmpereira/heroku-cl-example/blob/master/src/hello-world.lisp)

``` lisp
(heroku-getenv "PWD") => /app/tmp/repo.git

(heroku-getenv "HOME") => /app/
```

I'm sticking with $HOME for the time being 8e0a6bdb5a046d486a1febbed42d52de213517f3 .

**Comment by yfeldblum** [comment]
Your application should run correctly, with no code changes at all, when deployed in any supported environment:
- heroku, at /app
- your workstation, at /home/yourname/work/company/projects/clproj
- your CI server, at /tmp/ci-run-19923
